# all profiles
logging.level:
    org.springframework: INFO
    org.hibernate: WARN


---
# profile "injectedProperty" only
spring.profiles: injectedProperty

customproperty: customPropValue

---
# profile "daoConfig" only
spring:
  profiles: daoConfig

  datasource:
    schema: classpath:/database/schema.sql
